/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_p2_serliogiron;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Button;
import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Label;
import java.awt.Point;
import java.awt.TextArea;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DropMode;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.swing.text.TableView;

/**
 *
 * @author usuario
 */
public class Main extends javax.swing.JFrame implements MouseListener, MouseMotionListener, Printable{

    /**
     * Creates new form Main
     */
    
    public void ponerFoto(String fotonombre, int x, int y, JButton boton){
        ImageIcon colortext = new ImageIcon(fotonombre);
        
        Image foto = colortext.getImage();
        Image fotobuena = foto.getScaledInstance(x, y, java.awt.Image.SCALE_SMOOTH);
        colortext = new ImageIcon(fotobuena);
        boton.setIcon(colortext);
    }
    
    public Main() {
        initComponents();
        
//        ImageIcon colortext = new ImageIcon("text-color.png");
//        
//        Image foto = colortext.getImage();
//        Image fotobuena = foto.getScaledInstance(32, 32, java.awt.Image.SCALE_SMOOTH);
//        colortext = new ImageIcon(fotobuena);
//        EditText.setIcon(colortext);
        
        ponerFoto("text-color.png",32,32,EditText);
        ponerFoto("tabla.png",57,40,clase);
        ponerFoto("impresora.jpg", 40, 35, Imprimir);
        System.out.println("hola");
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) combobox_fuentes.getModel();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Font fontNames[] = ge.getAllFonts();
        
        for (int i = 0; i < fontNames.length; i++) {
            modelo.addElement(fontNames[i]);
        }
        combobox_fuentes.setModel(modelo);
        
        DefaultComboBoxModel numeros = (DefaultComboBoxModel) combobox_tamano.getModel();
//        int numeros;
    }
    
    static JScrollPane scrollpaneglobal;
    static JTable tableglobal;
    
    Point startpoint;
    
    StyledDocument doc;
    Style estilo;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabla = new javax.swing.JTable();
        label = new javax.swing.JLabel();
        PopUp = new javax.swing.JPopupMenu();
        Agregar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        EliminarTabla = new javax.swing.JMenuItem();
        ColorChooser = new javax.swing.JColorChooser();
        Codigo = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        Background = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Editar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combobox_fuentes = new javax.swing.JComboBox<>();
        combobox_tamano = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        EditText = new javax.swing.JButton();
        Diagrama = new javax.swing.JPanel();
        Imprimir = new javax.swing.JButton();
        PNG = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        canva = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelazulUML = new javax.swing.JPanel();
        clase = new javax.swing.JButton();
        panelazulDiagrama = new javax.swing.JPanel();

        tabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre de Clase"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
        });

        label.setText("jLabel1");

        PopUp.setPreferredSize(new java.awt.Dimension(78, 90));

        Agregar.setText("Agregar");
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarMouseClicked(evt);
            }
        });
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        PopUp.add(Agregar);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        PopUp.add(Eliminar);

        EliminarTabla.setText("Eliminar Tabla");
        EliminarTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarTablaMouseClicked(evt);
            }
        });
        PopUp.add(EliminarTabla);

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane2.setViewportView(TextArea);

        javax.swing.GroupLayout CodigoLayout = new javax.swing.GroupLayout(Codigo.getContentPane());
        Codigo.getContentPane().setLayout(CodigoLayout);
        CodigoLayout.setHorizontalGroup(
            CodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CodigoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        CodigoLayout.setVerticalGroup(
            CodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CodigoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(16, 9));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(800, 800));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 225, 225), 1, true));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 255));
        jTabbedPane2.setAutoscrolls(true);
        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane2.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(800, 103));

        Editar.setBackground(new java.awt.Color(255, 255, 255));
        Editar.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Fuente: ");

        jLabel2.setText("Tamaño: ");

        combobox_fuentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combobox_fuentesMouseClicked(evt);
            }
        });

        combobox_tamano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "10", "12", "14", "16", "20", "24", "36", "44" }));

        jLabel3.setText("Color: ");

        jButton1.setBackground(java.awt.Color.red);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.magenta);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setBackground(java.awt.Color.cyan);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton5.setBackground(java.awt.Color.blue);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setBackground(java.awt.Color.yellow);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setBackground(java.awt.Color.green);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setBackground(java.awt.Color.lightGray);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton4.setBackground(java.awt.Color.darkGray);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton9.setBackground(java.awt.Color.pink);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setBackground(java.awt.Color.orange);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton11.setBackground(java.awt.Color.black);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jButton12.setBackground(java.awt.Color.gray);
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        EditText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EditarLayout = new javax.swing.GroupLayout(Editar);
        Editar.setLayout(EditarLayout);
        EditarLayout.setHorizontalGroup(
            EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(combobox_fuentes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(combobox_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(EditText))
        );
        EditarLayout.setVerticalGroup(
            EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1))
            .addGroup(EditarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(combobox_fuentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(EditarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2))
            .addGroup(EditarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(combobox_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(EditarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3))
            .addGroup(EditarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(EditarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(EditarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(EditarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(EditarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(EditarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(EditarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(EditText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Editar", Editar);

        Diagrama.setBackground(new java.awt.Color(255, 255, 255));
        Diagrama.setForeground(new java.awt.Color(255, 255, 255));

        Imprimir.setBackground(new java.awt.Color(255, 255, 255));
        Imprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImprimirMouseClicked(evt);
            }
        });

        PNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNGActionPerformed(evt);
            }
        });

        jButton13.setText("jButton13");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DiagramaLayout = new javax.swing.GroupLayout(Diagrama);
        Diagrama.setLayout(DiagramaLayout);
        DiagramaLayout.setHorizontalGroup(
            DiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiagramaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PNG, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton13)
                .addContainerGap(569, Short.MAX_VALUE))
        );
        DiagramaLayout.setVerticalGroup(
            DiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiagramaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(DiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DiagramaLayout.createSequentialGroup()
                        .addComponent(jButton13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PNG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Imprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Archivo", Diagrama);

        canva.setBackground(new java.awt.Color(255, 255, 255));
        canva.setPreferredSize(new java.awt.Dimension(679, 474));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 255));

        panelazulUML.setBackground(new java.awt.Color(36, 36, 204));
        panelazulUML.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        panelazulUML.setPreferredSize(new java.awt.Dimension(134, 500));

        clase.setBackground(new java.awt.Color(255, 255, 255));
        clase.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                claseMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                claseMouseMoved(evt);
            }
        });
        clase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                claseMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                claseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                claseMouseReleased(evt);
            }
        });
        clase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelazulUMLLayout = new javax.swing.GroupLayout(panelazulUML);
        panelazulUML.setLayout(panelazulUMLLayout);
        panelazulUMLLayout.setHorizontalGroup(
            panelazulUMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelazulUMLLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(clase, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelazulUMLLayout.setVerticalGroup(
            panelazulUMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelazulUMLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clase, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("UML", panelazulUML);

        panelazulDiagrama.setBackground(new java.awt.Color(36, 36, 204));
        panelazulDiagrama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        panelazulDiagrama.setPreferredSize(new java.awt.Dimension(134, 500));

        javax.swing.GroupLayout panelazulDiagramaLayout = new javax.swing.GroupLayout(panelazulDiagrama);
        panelazulDiagrama.setLayout(panelazulDiagramaLayout);
        panelazulDiagramaLayout.setHorizontalGroup(
            panelazulDiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );
        panelazulDiagramaLayout.setVerticalGroup(
            panelazulDiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Diagrama", panelazulDiagrama);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canva, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void claseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseActionPerformed
//        label.setVisible(true);
//        canva.add(label);
//        canva.revalidate();
//        canva.repaint();

        CrearTable();
    }//GEN-LAST:event_claseActionPerformed
    ArrayList <JTable> tablas = new ArrayList();
    
    public void CrearTable(){
        DefaultTableModel modelo = new DefaultTableModel();
        
        Object[] rowdata = new Object[4];
        
//        for (int i = 0; i < 4; i++) {
//            rowdata[i] = "";
//        }
        
        modelo.setColumnCount(1);
        modelo.setRowCount(4);

        JTable tablaaux = new JTable(modelo);
        
        //tablaaux = tabla;
        
        tablaaux.setBorder(tabla.getBorder());
        tablaaux.setAutoResizeMode(WIDTH);


        //JScrollPane tablaaux = new JScrollPane();
        
        //tablaaux = tabla;
        
        //startpoint = null;
        
        //tablaaux.add(new JTable(tabla.getModel()));
        
        tablaaux.setVisible(true);
        tablaaux.addMouseListener(this);
        tablaaux.addMouseMotionListener(this);
        tableglobal = tablaaux;
        canva.add(tablaaux);
        canva.revalidate();
        canva.repaint();
        
        System.out.println(tablaaux);
    }
    
    
    private void claseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claseMouseClicked
        
    }//GEN-LAST:event_claseMouseClicked

    private void claseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claseMouseDragged
        
        
        System.out.println("Mouse dragged");
    }//GEN-LAST:event_claseMouseDragged

    private void claseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claseMouseMoved
        //System.out.println("mouse moved");
    }//GEN-LAST:event_claseMouseMoved

    private void claseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claseMouseReleased
        

        

        System.out.println("Muse released");
    }//GEN-LAST:event_claseMouseReleased

    private void claseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claseMousePressed
        System.out.println("mouse pressed");
        
        //Background.getMousePosition()
        
//        
    }//GEN-LAST:event_claseMousePressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        Colorearbackgrounf((JButton) evt.getComponent());
    }//GEN-LAST:event_jButton1MouseClicked

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        
        
        if (evt.isMetaDown()) {
            PopUp.pack();
            //PopUp.setVisible(true);
            PopUp.show(evt.getComponent(),evt.getX(), evt.getY());
            System.out.println("if metadown");
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Colorearbackgrounf((JButton) evt.getComponent());
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        Colorearbackgrounf((JButton) evt.getComponent());
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        Colorearbackgrounf((JButton) evt.getComponent());
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        Colorearbackgrounf((JButton) evt.getComponent());
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        Colorearbackgrounf((JButton) evt.getComponent());
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        Colorearbackgrounf((JButton) evt.getComponent());
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Colorearbackgrounf((JButton) evt.getComponent());
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        Colorearbackgrounf((JButton) evt.getComponent());
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        Colorearbackgrounf((JButton) evt.getComponent());
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Colorearbackgrounf((JButton) evt.getComponent());
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        Colorearbackgrounf((JButton) evt.getComponent());
    }//GEN-LAST:event_jButton8MouseClicked

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) tableglobal.getModel();
        
        Object[] rowdata = new Object[1];
        rowdata[0] = "";
        modelo.addRow(rowdata);
        
        tableglobal.setModel(modelo);
    }//GEN-LAST:event_AgregarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo = (DefaultTableModel)tableglobal.getModel();
        
        modelo.removeRow(tableglobal.getSelectedRow());
        
        tableglobal.setModel(modelo);
        
        //tableglobal.revalidate();
        //tableglobal.repaint();
    }//GEN-LAST:event_EliminarActionPerformed

    private void AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseClicked
        
        Object rowData[] = new Object[1];
        rowData[0] = "";
        
        DefaultTableModel m = new DefaultTableModel();
        
        m = (DefaultTableModel)tableglobal.getModel();
        
        m.addRow(rowData);
        
        tableglobal.setModel(m);
        
        //tableglobal.revalidate();
        //tableglobal.repaint();
    }//GEN-LAST:event_AgregarMouseClicked

    private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed
        //tableglobal = (JTable)evt.getComponent();
        
        System.out.println("Mouse pressed tabla");
    }//GEN-LAST:event_tablaMousePressed

    private void combobox_fuentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combobox_fuentesMouseClicked
        //tableglobal.getComponent(tableglobal.getSelectedRow()).setFont((Font)combobox_fuentes.getSelectedItem());
        tableglobal.setFont((Font)combobox_fuentes.getSelectedItem());
        
        //tableglobal.revalidate();
        //tableglobal.repaint();
    }//GEN-LAST:event_combobox_fuentesMouseClicked

    private void EditTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTextMouseClicked
        ColorChooser.show();
    }//GEN-LAST:event_EditTextMouseClicked

    private void EliminarTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarTablaMouseClicked
        DefaultTableModel m = new DefaultTableModel();
        m = (DefaultTableModel)tableglobal.getModel();
        
        for (int i = 0; i < m.getRowCount(); i++) {
            m.removeRow(i);
        }
        
        tableglobal.setModel(m);
    }//GEN-LAST:event_EliminarTablaMouseClicked

    private void ImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImprimirMouseClicked
        printRecord(canva);
    }//GEN-LAST:event_ImprimirMouseClicked

    private void PNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNGActionPerformed
        
    }//GEN-LAST:event_PNGActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
    
        
        String texto = "";
        
        for (int i = 0; i < canva.getComponentCount(); i++) {
            JTable temp = new JTable();
            
            temp = (JTable)canva.getComponent(i);
            
            for (int j = 0; j < temp.getRowCount(); j++) {
                System.out.println(i + " Row: " + temp.getValueAt(j, 0));
            }
            
            System.out.println("");
            
            texto += texto(temp);
        }
        
        TextArea.setText(texto);
        Codigo.pack();
        Codigo.setVisible(true);
        
    }//GEN-LAST:event_jButton13ActionPerformed
    
    public String texto(JTable tabla){
        String temp = "";
        
        temp += "class " + tabla.getValueAt(0, 0) + "{ \n";
        
        for (int i = 1; i < tabla.getRowCount(); i++) {
            
            temp += "\t" + tabla.getValueAt(i, 0) + "\n";
            
        }
        
        return temp;
    }
    
    
    
//    public void saveImage(String name,String type) {
//		BufferedImage image = new BufferedImage(getWidth(),getHeight(), BufferedImage.TYPE_INT_RGB);
//		Graphics2D g2 = image.createGraphics();
//		paint(g2);
//		try{
//			ImageIO.write(image, type, new File(name+"."+type));
//		} catch (Exception e) {
//			e.printStackTrace();
//		}
//	}
//
//
//	public void paintComponent(Graphics g) {
//		super.paintComponent(g);
//	}
    
    public void printRecord (JPanel panel){
        PrinterJob printerjob = PrinterJob.getPrinterJob();
        
        printerjob.setJobName("Print Record");
        
        printerjob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            
                Graphics2D graphics2d = (Graphics2D)graphics;
                graphics2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
                graphics2d.scale(0.5, 0.5);
                panel.paint(graphics2d);
                return Printable.PAGE_EXISTS;
            }
        });
        
        boolean returningRsult = printerjob.printDialog();
        
        if (returningRsult) {
            try {
                printerjob.print();
            } catch (Exception e) {
            }
        }
    }
    
    
    public static void Colorearbackgrounf(JButton b){
        //scrollpaneglobal.getComponent(0).setBackground(b.getBackground());
        
        System.out.println("colorear backgroundf");
        System.out.println("boton: " + b.getBackground());
        System.out.println("tabla: " + tableglobal);
        
        tableglobal.setBackground(b.getBackground());
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Agregar;
    private javax.swing.JPanel Background;
    private javax.swing.JDialog Codigo;
    private javax.swing.JColorChooser ColorChooser;
    private javax.swing.JPanel Diagrama;
    private javax.swing.JButton EditText;
    private javax.swing.JPanel Editar;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem EliminarTabla;
    private javax.swing.JButton Imprimir;
    private javax.swing.JButton PNG;
    private javax.swing.JPopupMenu PopUp;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JPanel canva;
    private javax.swing.JButton clase;
    private javax.swing.JComboBox<String> combobox_fuentes;
    private javax.swing.JComboBox<String> combobox_tamano;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel label;
    private javax.swing.JPanel panelazulDiagrama;
    private javax.swing.JPanel panelazulUML;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet.");
        //To change body of generated methods, choose Tools | Templates.
        
        //------- POP UP MENU ------
        if (e.getComponent() instanceof JTable) {
            if (e.isMetaDown()) {
                PopUp.pack();
                //PopUp.setVisible(true);
                PopUp.show(e.getComponent(),e.getX(), e.getY());
                System.out.println("if metadown");
            }
        }
        
        
    }

    @Override
    public void mousePressed(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet.");
        //To change body of generated methods, choose Tools | Templates.
        
        if (e.getComponent() instanceof JTable) {
            tableglobal = (JTable)e.getComponent();
        }
        
        startpoint = SwingUtilities.convertPoint(e.getComponent(), e.getPoint(), e.getComponent().getParent());
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
        
        startpoint = null;
        
//        throw new UnsupportedOperationException("Not supported yet.");
        //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet.");
        //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet.");
        //To change body of generated methods, choose Tools | Templates.
        //startpoint = null;
    }

    @Override
    public void mouseDragged(MouseEvent e) {
        
        Point location = SwingUtilities.convertPoint(e.getComponent(), e.getPoint(), e.getComponent().getParent());
        if (e.getComponent().getParent().getBounds().contains(location)) {
            Point newLocation = e.getComponent().getLocation();
            newLocation.translate(location.x - startpoint.x, location.y - startpoint.y);
            newLocation.x = Math.max(newLocation.x, 0);
            newLocation.y = Math.max(newLocation.y, 0);
            newLocation.x = Math.min(newLocation.x, e.getComponent().getParent().getWidth() - e.getComponent().getWidth());
            newLocation.y = Math.min(newLocation.y, e.getComponent().getParent().getHeight() - e.getComponent().getHeight());
            e.getComponent().setLocation(newLocation);
            startpoint = location;
        }
        
//        throw new UnsupportedOperationException("Not supported yet.");
        //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseMoved(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet.");
        //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
